// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store/common.proto

package com.cloud.app.proto;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.cloud.app.proto.RowStatus}
   */
  public enum RowStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ROW_STATUS_UNSPECIFIED = 0;</code>
     */
    ROW_STATUS_UNSPECIFIED(0),
    /**
     * <code>NORMAL = 1;</code>
     */
    NORMAL(1),
    /**
     * <code>ARCHIVED = 2;</code>
     */
    ARCHIVED(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ROW_STATUS_UNSPECIFIED = 0;</code>
     */
    public static final int ROW_STATUS_UNSPECIFIED_VALUE = 0;
    /**
     * <code>NORMAL = 1;</code>
     */
    public static final int NORMAL_VALUE = 1;
    /**
     * <code>ARCHIVED = 2;</code>
     */
    public static final int ARCHIVED_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RowStatus valueOf(int value) {
      return forNumber(value);
    }

    public static RowStatus forNumber(int value) {
      switch (value) {
        case 0: return ROW_STATUS_UNSPECIFIED;
        case 1: return NORMAL;
        case 2: return ARCHIVED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RowStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RowStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RowStatus>() {
            public RowStatus findValueByNumber(int number) {
              return RowStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.cloud.app.proto.Common.getDescriptor().getEnumTypes().get(0);
    }

    private static final RowStatus[] VALUES = values();

    public static RowStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RowStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.cloud.app.proto.RowStatus)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022store/common.proto\022\023com.cloud.app.prot" +
      "o*A\n\tRowStatus\022\032\n\026ROW_STATUS_UNSPECIFIED" +
      "\020\000\022\n\n\006NORMAL\020\001\022\014\n\010ARCHIVED\020\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
