// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.cloud.app.proto;

public interface CreateUserAccessTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cloud.app.proto.CreateUserAccessTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.cloud.app.proto.UserAccessToken access_token = 1;</code>
   */
  boolean hasAccessToken();
  /**
   * <code>.com.cloud.app.proto.UserAccessToken access_token = 1;</code>
   */
  com.cloud.app.proto.UserAccessToken getAccessToken();
  /**
   * <code>.com.cloud.app.proto.UserAccessToken access_token = 1;</code>
   */
  com.cloud.app.proto.UserAccessTokenOrBuilder getAccessTokenOrBuilder();
}
