// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.cloud.app.proto;

public interface CreateUserAccessTokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cloud.app.proto.CreateUserAccessTokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the user.
   * Format: users/{username}
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the user.
   * Format: users/{username}
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 2;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>.google.protobuf.Timestamp expires_at = 3;</code>
   */
  boolean hasExpiresAt();
  /**
   * <code>.google.protobuf.Timestamp expires_at = 3;</code>
   */
  com.google.protobuf.Timestamp getExpiresAt();
  /**
   * <code>.google.protobuf.Timestamp expires_at = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpiresAtOrBuilder();
}
