// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.cloud.app.proto;

public interface DeleteUserAccessTokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cloud.app.proto.DeleteUserAccessTokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the user.
   * Format: users/{username}
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the user.
   * Format: users/{username}
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * access_token is the access token to delete.
   * </pre>
   *
   * <code>string access_token = 2;</code>
   */
  java.lang.String getAccessToken();
  /**
   * <pre>
   * access_token is the access token to delete.
   * </pre>
   *
   * <code>string access_token = 2;</code>
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();
}
