// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.cloud.app.proto;

public interface DeleteUserAccessTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cloud.app.proto.DeleteUserAccessTokenResponse)
    com.google.protobuf.MessageOrBuilder {
}
