// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.cloud.app.proto;

public interface GetUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cloud.app.proto.GetUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.cloud.app.proto.User user = 1;</code>
   */
  boolean hasUser();
  /**
   * <code>.com.cloud.app.proto.User user = 1;</code>
   */
  com.cloud.app.proto.User getUser();
  /**
   * <code>.com.cloud.app.proto.User user = 1;</code>
   */
  com.cloud.app.proto.UserOrBuilder getUserOrBuilder();
}
