// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.cloud.app.proto;

public interface GetUserSettingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cloud.app.proto.GetUserSettingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the user.
   * Format: users/{username}
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the user.
   * Format: users/{username}
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
