// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.cloud.app.proto;

public interface GetUserSettingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cloud.app.proto.GetUserSettingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.cloud.app.proto.UserSetting setting = 1;</code>
   */
  boolean hasSetting();
  /**
   * <code>.com.cloud.app.proto.UserSetting setting = 1;</code>
   */
  com.cloud.app.proto.UserSetting getSetting();
  /**
   * <code>.com.cloud.app.proto.UserSetting setting = 1;</code>
   */
  com.cloud.app.proto.UserSettingOrBuilder getSettingOrBuilder();
}
