// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.cloud.app.proto;

/**
 * Protobuf type {@code com.cloud.app.proto.GetUserSettingResponse}
 */
public  final class GetUserSettingResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.cloud.app.proto.GetUserSettingResponse)
    GetUserSettingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetUserSettingResponse.newBuilder() to construct.
  private GetUserSettingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetUserSettingResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetUserSettingResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.cloud.app.proto.UserSetting.Builder subBuilder = null;
            if (setting_ != null) {
              subBuilder = setting_.toBuilder();
            }
            setting_ = input.readMessage(com.cloud.app.proto.UserSetting.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(setting_);
              setting_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_GetUserSettingResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_GetUserSettingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cloud.app.proto.GetUserSettingResponse.class, com.cloud.app.proto.GetUserSettingResponse.Builder.class);
  }

  public static final int SETTING_FIELD_NUMBER = 1;
  private com.cloud.app.proto.UserSetting setting_;
  /**
   * <code>.com.cloud.app.proto.UserSetting setting = 1;</code>
   */
  public boolean hasSetting() {
    return setting_ != null;
  }
  /**
   * <code>.com.cloud.app.proto.UserSetting setting = 1;</code>
   */
  public com.cloud.app.proto.UserSetting getSetting() {
    return setting_ == null ? com.cloud.app.proto.UserSetting.getDefaultInstance() : setting_;
  }
  /**
   * <code>.com.cloud.app.proto.UserSetting setting = 1;</code>
   */
  public com.cloud.app.proto.UserSettingOrBuilder getSettingOrBuilder() {
    return getSetting();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (setting_ != null) {
      output.writeMessage(1, getSetting());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (setting_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSetting());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cloud.app.proto.GetUserSettingResponse)) {
      return super.equals(obj);
    }
    com.cloud.app.proto.GetUserSettingResponse other = (com.cloud.app.proto.GetUserSettingResponse) obj;

    boolean result = true;
    result = result && (hasSetting() == other.hasSetting());
    if (hasSetting()) {
      result = result && getSetting()
          .equals(other.getSetting());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSetting()) {
      hash = (37 * hash) + SETTING_FIELD_NUMBER;
      hash = (53 * hash) + getSetting().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cloud.app.proto.GetUserSettingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cloud.app.proto.GetUserSettingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cloud.app.proto.GetUserSettingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cloud.app.proto.GetUserSettingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cloud.app.proto.GetUserSettingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cloud.app.proto.GetUserSettingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cloud.app.proto.GetUserSettingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cloud.app.proto.GetUserSettingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cloud.app.proto.GetUserSettingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cloud.app.proto.GetUserSettingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cloud.app.proto.GetUserSettingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cloud.app.proto.GetUserSettingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cloud.app.proto.GetUserSettingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.cloud.app.proto.GetUserSettingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.cloud.app.proto.GetUserSettingResponse)
      com.cloud.app.proto.GetUserSettingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_GetUserSettingResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_GetUserSettingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloud.app.proto.GetUserSettingResponse.class, com.cloud.app.proto.GetUserSettingResponse.Builder.class);
    }

    // Construct using com.cloud.app.proto.GetUserSettingResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (settingBuilder_ == null) {
        setting_ = null;
      } else {
        setting_ = null;
        settingBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_GetUserSettingResponse_descriptor;
    }

    public com.cloud.app.proto.GetUserSettingResponse getDefaultInstanceForType() {
      return com.cloud.app.proto.GetUserSettingResponse.getDefaultInstance();
    }

    public com.cloud.app.proto.GetUserSettingResponse build() {
      com.cloud.app.proto.GetUserSettingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.cloud.app.proto.GetUserSettingResponse buildPartial() {
      com.cloud.app.proto.GetUserSettingResponse result = new com.cloud.app.proto.GetUserSettingResponse(this);
      if (settingBuilder_ == null) {
        result.setting_ = setting_;
      } else {
        result.setting_ = settingBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cloud.app.proto.GetUserSettingResponse) {
        return mergeFrom((com.cloud.app.proto.GetUserSettingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cloud.app.proto.GetUserSettingResponse other) {
      if (other == com.cloud.app.proto.GetUserSettingResponse.getDefaultInstance()) return this;
      if (other.hasSetting()) {
        mergeSetting(other.getSetting());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cloud.app.proto.GetUserSettingResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cloud.app.proto.GetUserSettingResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.cloud.app.proto.UserSetting setting_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cloud.app.proto.UserSetting, com.cloud.app.proto.UserSetting.Builder, com.cloud.app.proto.UserSettingOrBuilder> settingBuilder_;
    /**
     * <code>.com.cloud.app.proto.UserSetting setting = 1;</code>
     */
    public boolean hasSetting() {
      return settingBuilder_ != null || setting_ != null;
    }
    /**
     * <code>.com.cloud.app.proto.UserSetting setting = 1;</code>
     */
    public com.cloud.app.proto.UserSetting getSetting() {
      if (settingBuilder_ == null) {
        return setting_ == null ? com.cloud.app.proto.UserSetting.getDefaultInstance() : setting_;
      } else {
        return settingBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.cloud.app.proto.UserSetting setting = 1;</code>
     */
    public Builder setSetting(com.cloud.app.proto.UserSetting value) {
      if (settingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        setting_ = value;
        onChanged();
      } else {
        settingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.cloud.app.proto.UserSetting setting = 1;</code>
     */
    public Builder setSetting(
        com.cloud.app.proto.UserSetting.Builder builderForValue) {
      if (settingBuilder_ == null) {
        setting_ = builderForValue.build();
        onChanged();
      } else {
        settingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.cloud.app.proto.UserSetting setting = 1;</code>
     */
    public Builder mergeSetting(com.cloud.app.proto.UserSetting value) {
      if (settingBuilder_ == null) {
        if (setting_ != null) {
          setting_ =
            com.cloud.app.proto.UserSetting.newBuilder(setting_).mergeFrom(value).buildPartial();
        } else {
          setting_ = value;
        }
        onChanged();
      } else {
        settingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.cloud.app.proto.UserSetting setting = 1;</code>
     */
    public Builder clearSetting() {
      if (settingBuilder_ == null) {
        setting_ = null;
        onChanged();
      } else {
        setting_ = null;
        settingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.cloud.app.proto.UserSetting setting = 1;</code>
     */
    public com.cloud.app.proto.UserSetting.Builder getSettingBuilder() {
      
      onChanged();
      return getSettingFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.cloud.app.proto.UserSetting setting = 1;</code>
     */
    public com.cloud.app.proto.UserSettingOrBuilder getSettingOrBuilder() {
      if (settingBuilder_ != null) {
        return settingBuilder_.getMessageOrBuilder();
      } else {
        return setting_ == null ?
            com.cloud.app.proto.UserSetting.getDefaultInstance() : setting_;
      }
    }
    /**
     * <code>.com.cloud.app.proto.UserSetting setting = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cloud.app.proto.UserSetting, com.cloud.app.proto.UserSetting.Builder, com.cloud.app.proto.UserSettingOrBuilder> 
        getSettingFieldBuilder() {
      if (settingBuilder_ == null) {
        settingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.cloud.app.proto.UserSetting, com.cloud.app.proto.UserSetting.Builder, com.cloud.app.proto.UserSettingOrBuilder>(
                getSetting(),
                getParentForChildren(),
                isClean());
        setting_ = null;
      }
      return settingBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.cloud.app.proto.GetUserSettingResponse)
  }

  // @@protoc_insertion_point(class_scope:com.cloud.app.proto.GetUserSettingResponse)
  private static final com.cloud.app.proto.GetUserSettingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cloud.app.proto.GetUserSettingResponse();
  }

  public static com.cloud.app.proto.GetUserSettingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetUserSettingResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetUserSettingResponse>() {
    public GetUserSettingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetUserSettingResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetUserSettingResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetUserSettingResponse> getParserForType() {
    return PARSER;
  }

  public com.cloud.app.proto.GetUserSettingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

