// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.cloud.app.proto;

/**
 * Protobuf type {@code com.cloud.app.proto.ListUserAccessTokensResponse}
 */
public  final class ListUserAccessTokensResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.cloud.app.proto.ListUserAccessTokensResponse)
    ListUserAccessTokensResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListUserAccessTokensResponse.newBuilder() to construct.
  private ListUserAccessTokensResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListUserAccessTokensResponse() {
    accessTokens_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListUserAccessTokensResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              accessTokens_ = new java.util.ArrayList<com.cloud.app.proto.UserAccessToken>();
              mutable_bitField0_ |= 0x00000001;
            }
            accessTokens_.add(
                input.readMessage(com.cloud.app.proto.UserAccessToken.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        accessTokens_ = java.util.Collections.unmodifiableList(accessTokens_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_ListUserAccessTokensResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_ListUserAccessTokensResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cloud.app.proto.ListUserAccessTokensResponse.class, com.cloud.app.proto.ListUserAccessTokensResponse.Builder.class);
  }

  public static final int ACCESS_TOKENS_FIELD_NUMBER = 1;
  private java.util.List<com.cloud.app.proto.UserAccessToken> accessTokens_;
  /**
   * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
   */
  public java.util.List<com.cloud.app.proto.UserAccessToken> getAccessTokensList() {
    return accessTokens_;
  }
  /**
   * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
   */
  public java.util.List<? extends com.cloud.app.proto.UserAccessTokenOrBuilder> 
      getAccessTokensOrBuilderList() {
    return accessTokens_;
  }
  /**
   * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
   */
  public int getAccessTokensCount() {
    return accessTokens_.size();
  }
  /**
   * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
   */
  public com.cloud.app.proto.UserAccessToken getAccessTokens(int index) {
    return accessTokens_.get(index);
  }
  /**
   * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
   */
  public com.cloud.app.proto.UserAccessTokenOrBuilder getAccessTokensOrBuilder(
      int index) {
    return accessTokens_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < accessTokens_.size(); i++) {
      output.writeMessage(1, accessTokens_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < accessTokens_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, accessTokens_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cloud.app.proto.ListUserAccessTokensResponse)) {
      return super.equals(obj);
    }
    com.cloud.app.proto.ListUserAccessTokensResponse other = (com.cloud.app.proto.ListUserAccessTokensResponse) obj;

    boolean result = true;
    result = result && getAccessTokensList()
        .equals(other.getAccessTokensList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAccessTokensCount() > 0) {
      hash = (37 * hash) + ACCESS_TOKENS_FIELD_NUMBER;
      hash = (53 * hash) + getAccessTokensList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cloud.app.proto.ListUserAccessTokensResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cloud.app.proto.ListUserAccessTokensResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cloud.app.proto.ListUserAccessTokensResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cloud.app.proto.ListUserAccessTokensResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cloud.app.proto.ListUserAccessTokensResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cloud.app.proto.ListUserAccessTokensResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cloud.app.proto.ListUserAccessTokensResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cloud.app.proto.ListUserAccessTokensResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cloud.app.proto.ListUserAccessTokensResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cloud.app.proto.ListUserAccessTokensResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cloud.app.proto.ListUserAccessTokensResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cloud.app.proto.ListUserAccessTokensResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cloud.app.proto.ListUserAccessTokensResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.cloud.app.proto.ListUserAccessTokensResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.cloud.app.proto.ListUserAccessTokensResponse)
      com.cloud.app.proto.ListUserAccessTokensResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_ListUserAccessTokensResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_ListUserAccessTokensResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloud.app.proto.ListUserAccessTokensResponse.class, com.cloud.app.proto.ListUserAccessTokensResponse.Builder.class);
    }

    // Construct using com.cloud.app.proto.ListUserAccessTokensResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAccessTokensFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (accessTokensBuilder_ == null) {
        accessTokens_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        accessTokensBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_ListUserAccessTokensResponse_descriptor;
    }

    public com.cloud.app.proto.ListUserAccessTokensResponse getDefaultInstanceForType() {
      return com.cloud.app.proto.ListUserAccessTokensResponse.getDefaultInstance();
    }

    public com.cloud.app.proto.ListUserAccessTokensResponse build() {
      com.cloud.app.proto.ListUserAccessTokensResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.cloud.app.proto.ListUserAccessTokensResponse buildPartial() {
      com.cloud.app.proto.ListUserAccessTokensResponse result = new com.cloud.app.proto.ListUserAccessTokensResponse(this);
      int from_bitField0_ = bitField0_;
      if (accessTokensBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          accessTokens_ = java.util.Collections.unmodifiableList(accessTokens_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.accessTokens_ = accessTokens_;
      } else {
        result.accessTokens_ = accessTokensBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cloud.app.proto.ListUserAccessTokensResponse) {
        return mergeFrom((com.cloud.app.proto.ListUserAccessTokensResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cloud.app.proto.ListUserAccessTokensResponse other) {
      if (other == com.cloud.app.proto.ListUserAccessTokensResponse.getDefaultInstance()) return this;
      if (accessTokensBuilder_ == null) {
        if (!other.accessTokens_.isEmpty()) {
          if (accessTokens_.isEmpty()) {
            accessTokens_ = other.accessTokens_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAccessTokensIsMutable();
            accessTokens_.addAll(other.accessTokens_);
          }
          onChanged();
        }
      } else {
        if (!other.accessTokens_.isEmpty()) {
          if (accessTokensBuilder_.isEmpty()) {
            accessTokensBuilder_.dispose();
            accessTokensBuilder_ = null;
            accessTokens_ = other.accessTokens_;
            bitField0_ = (bitField0_ & ~0x00000001);
            accessTokensBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAccessTokensFieldBuilder() : null;
          } else {
            accessTokensBuilder_.addAllMessages(other.accessTokens_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cloud.app.proto.ListUserAccessTokensResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cloud.app.proto.ListUserAccessTokensResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.cloud.app.proto.UserAccessToken> accessTokens_ =
      java.util.Collections.emptyList();
    private void ensureAccessTokensIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        accessTokens_ = new java.util.ArrayList<com.cloud.app.proto.UserAccessToken>(accessTokens_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cloud.app.proto.UserAccessToken, com.cloud.app.proto.UserAccessToken.Builder, com.cloud.app.proto.UserAccessTokenOrBuilder> accessTokensBuilder_;

    /**
     * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
     */
    public java.util.List<com.cloud.app.proto.UserAccessToken> getAccessTokensList() {
      if (accessTokensBuilder_ == null) {
        return java.util.Collections.unmodifiableList(accessTokens_);
      } else {
        return accessTokensBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
     */
    public int getAccessTokensCount() {
      if (accessTokensBuilder_ == null) {
        return accessTokens_.size();
      } else {
        return accessTokensBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
     */
    public com.cloud.app.proto.UserAccessToken getAccessTokens(int index) {
      if (accessTokensBuilder_ == null) {
        return accessTokens_.get(index);
      } else {
        return accessTokensBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
     */
    public Builder setAccessTokens(
        int index, com.cloud.app.proto.UserAccessToken value) {
      if (accessTokensBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAccessTokensIsMutable();
        accessTokens_.set(index, value);
        onChanged();
      } else {
        accessTokensBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
     */
    public Builder setAccessTokens(
        int index, com.cloud.app.proto.UserAccessToken.Builder builderForValue) {
      if (accessTokensBuilder_ == null) {
        ensureAccessTokensIsMutable();
        accessTokens_.set(index, builderForValue.build());
        onChanged();
      } else {
        accessTokensBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
     */
    public Builder addAccessTokens(com.cloud.app.proto.UserAccessToken value) {
      if (accessTokensBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAccessTokensIsMutable();
        accessTokens_.add(value);
        onChanged();
      } else {
        accessTokensBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
     */
    public Builder addAccessTokens(
        int index, com.cloud.app.proto.UserAccessToken value) {
      if (accessTokensBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAccessTokensIsMutable();
        accessTokens_.add(index, value);
        onChanged();
      } else {
        accessTokensBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
     */
    public Builder addAccessTokens(
        com.cloud.app.proto.UserAccessToken.Builder builderForValue) {
      if (accessTokensBuilder_ == null) {
        ensureAccessTokensIsMutable();
        accessTokens_.add(builderForValue.build());
        onChanged();
      } else {
        accessTokensBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
     */
    public Builder addAccessTokens(
        int index, com.cloud.app.proto.UserAccessToken.Builder builderForValue) {
      if (accessTokensBuilder_ == null) {
        ensureAccessTokensIsMutable();
        accessTokens_.add(index, builderForValue.build());
        onChanged();
      } else {
        accessTokensBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
     */
    public Builder addAllAccessTokens(
        java.lang.Iterable<? extends com.cloud.app.proto.UserAccessToken> values) {
      if (accessTokensBuilder_ == null) {
        ensureAccessTokensIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, accessTokens_);
        onChanged();
      } else {
        accessTokensBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
     */
    public Builder clearAccessTokens() {
      if (accessTokensBuilder_ == null) {
        accessTokens_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        accessTokensBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
     */
    public Builder removeAccessTokens(int index) {
      if (accessTokensBuilder_ == null) {
        ensureAccessTokensIsMutable();
        accessTokens_.remove(index);
        onChanged();
      } else {
        accessTokensBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
     */
    public com.cloud.app.proto.UserAccessToken.Builder getAccessTokensBuilder(
        int index) {
      return getAccessTokensFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
     */
    public com.cloud.app.proto.UserAccessTokenOrBuilder getAccessTokensOrBuilder(
        int index) {
      if (accessTokensBuilder_ == null) {
        return accessTokens_.get(index);  } else {
        return accessTokensBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
     */
    public java.util.List<? extends com.cloud.app.proto.UserAccessTokenOrBuilder> 
         getAccessTokensOrBuilderList() {
      if (accessTokensBuilder_ != null) {
        return accessTokensBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(accessTokens_);
      }
    }
    /**
     * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
     */
    public com.cloud.app.proto.UserAccessToken.Builder addAccessTokensBuilder() {
      return getAccessTokensFieldBuilder().addBuilder(
          com.cloud.app.proto.UserAccessToken.getDefaultInstance());
    }
    /**
     * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
     */
    public com.cloud.app.proto.UserAccessToken.Builder addAccessTokensBuilder(
        int index) {
      return getAccessTokensFieldBuilder().addBuilder(
          index, com.cloud.app.proto.UserAccessToken.getDefaultInstance());
    }
    /**
     * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
     */
    public java.util.List<com.cloud.app.proto.UserAccessToken.Builder> 
         getAccessTokensBuilderList() {
      return getAccessTokensFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cloud.app.proto.UserAccessToken, com.cloud.app.proto.UserAccessToken.Builder, com.cloud.app.proto.UserAccessTokenOrBuilder> 
        getAccessTokensFieldBuilder() {
      if (accessTokensBuilder_ == null) {
        accessTokensBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.cloud.app.proto.UserAccessToken, com.cloud.app.proto.UserAccessToken.Builder, com.cloud.app.proto.UserAccessTokenOrBuilder>(
                accessTokens_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        accessTokens_ = null;
      }
      return accessTokensBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.cloud.app.proto.ListUserAccessTokensResponse)
  }

  // @@protoc_insertion_point(class_scope:com.cloud.app.proto.ListUserAccessTokensResponse)
  private static final com.cloud.app.proto.ListUserAccessTokensResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cloud.app.proto.ListUserAccessTokensResponse();
  }

  public static com.cloud.app.proto.ListUserAccessTokensResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListUserAccessTokensResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListUserAccessTokensResponse>() {
    public ListUserAccessTokensResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListUserAccessTokensResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListUserAccessTokensResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListUserAccessTokensResponse> getParserForType() {
    return PARSER;
  }

  public com.cloud.app.proto.ListUserAccessTokensResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

