// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.cloud.app.proto;

public interface ListUserAccessTokensResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cloud.app.proto.ListUserAccessTokensResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
   */
  java.util.List<com.cloud.app.proto.UserAccessToken> 
      getAccessTokensList();
  /**
   * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
   */
  com.cloud.app.proto.UserAccessToken getAccessTokens(int index);
  /**
   * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
   */
  int getAccessTokensCount();
  /**
   * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
   */
  java.util.List<? extends com.cloud.app.proto.UserAccessTokenOrBuilder> 
      getAccessTokensOrBuilderList();
  /**
   * <code>repeated .com.cloud.app.proto.UserAccessToken access_tokens = 1;</code>
   */
  com.cloud.app.proto.UserAccessTokenOrBuilder getAccessTokensOrBuilder(
      int index);
}
