// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.cloud.app.proto;

public interface ListUsersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cloud.app.proto.ListUsersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.cloud.app.proto.User users = 1;</code>
   */
  java.util.List<com.cloud.app.proto.User> 
      getUsersList();
  /**
   * <code>repeated .com.cloud.app.proto.User users = 1;</code>
   */
  com.cloud.app.proto.User getUsers(int index);
  /**
   * <code>repeated .com.cloud.app.proto.User users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .com.cloud.app.proto.User users = 1;</code>
   */
  java.util.List<? extends com.cloud.app.proto.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .com.cloud.app.proto.User users = 1;</code>
   */
  com.cloud.app.proto.UserOrBuilder getUsersOrBuilder(
      int index);
}
