// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.cloud.app.proto;

public interface UpdateUserSettingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cloud.app.proto.UpdateUserSettingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * [(google.api.field_behavior) = REQUIRED]
   * </pre>
   *
   * <code>.com.cloud.app.proto.UserSetting setting = 1;</code>
   */
  boolean hasSetting();
  /**
   * <pre>
   * [(google.api.field_behavior) = REQUIRED]
   * </pre>
   *
   * <code>.com.cloud.app.proto.UserSetting setting = 1;</code>
   */
  com.cloud.app.proto.UserSetting getSetting();
  /**
   * <pre>
   * [(google.api.field_behavior) = REQUIRED]
   * </pre>
   *
   * <code>.com.cloud.app.proto.UserSetting setting = 1;</code>
   */
  com.cloud.app.proto.UserSettingOrBuilder getSettingOrBuilder();

  /**
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   */
  boolean hasUpdateMask();
  /**
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   */
  com.google.protobuf.FieldMask getUpdateMask();
  /**
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder();
}
