// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.cloud.app.proto;

/**
 * Protobuf type {@code com.cloud.app.proto.UserSetting}
 */
public  final class UserSetting extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.cloud.app.proto.UserSetting)
    UserSettingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserSetting.newBuilder() to construct.
  private UserSetting(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserSetting() {
    name_ = "";
    locale_ = "";
    appearance_ = "";
    memoVisibility_ = "";
    telegramUserId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserSetting(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            locale_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            appearance_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            memoVisibility_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            telegramUserId_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_UserSetting_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_UserSetting_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cloud.app.proto.UserSetting.class, com.cloud.app.proto.UserSetting.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * The name of the user.
   * Format: users/{username}
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The name of the user.
   * Format: users/{username}
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCALE_FIELD_NUMBER = 2;
  private volatile java.lang.Object locale_;
  /**
   * <pre>
   * The preferred locale of the user.
   * </pre>
   *
   * <code>string locale = 2;</code>
   */
  public java.lang.String getLocale() {
    java.lang.Object ref = locale_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      locale_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The preferred locale of the user.
   * </pre>
   *
   * <code>string locale = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLocaleBytes() {
    java.lang.Object ref = locale_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      locale_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPEARANCE_FIELD_NUMBER = 3;
  private volatile java.lang.Object appearance_;
  /**
   * <pre>
   * The preferred appearance of the user.
   * </pre>
   *
   * <code>string appearance = 3;</code>
   */
  public java.lang.String getAppearance() {
    java.lang.Object ref = appearance_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appearance_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The preferred appearance of the user.
   * </pre>
   *
   * <code>string appearance = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAppearanceBytes() {
    java.lang.Object ref = appearance_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appearance_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEMO_VISIBILITY_FIELD_NUMBER = 4;
  private volatile java.lang.Object memoVisibility_;
  /**
   * <pre>
   * The default visibility of the memo.
   * </pre>
   *
   * <code>string memo_visibility = 4;</code>
   */
  public java.lang.String getMemoVisibility() {
    java.lang.Object ref = memoVisibility_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      memoVisibility_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The default visibility of the memo.
   * </pre>
   *
   * <code>string memo_visibility = 4;</code>
   */
  public com.google.protobuf.ByteString
      getMemoVisibilityBytes() {
    java.lang.Object ref = memoVisibility_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      memoVisibility_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TELEGRAM_USER_ID_FIELD_NUMBER = 5;
  private volatile java.lang.Object telegramUserId_;
  /**
   * <pre>
   * The telegram user id of the user.
   * </pre>
   *
   * <code>string telegram_user_id = 5;</code>
   */
  public java.lang.String getTelegramUserId() {
    java.lang.Object ref = telegramUserId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      telegramUserId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The telegram user id of the user.
   * </pre>
   *
   * <code>string telegram_user_id = 5;</code>
   */
  public com.google.protobuf.ByteString
      getTelegramUserIdBytes() {
    java.lang.Object ref = telegramUserId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      telegramUserId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getLocaleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, locale_);
    }
    if (!getAppearanceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, appearance_);
    }
    if (!getMemoVisibilityBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, memoVisibility_);
    }
    if (!getTelegramUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, telegramUserId_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getLocaleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, locale_);
    }
    if (!getAppearanceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, appearance_);
    }
    if (!getMemoVisibilityBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, memoVisibility_);
    }
    if (!getTelegramUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, telegramUserId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cloud.app.proto.UserSetting)) {
      return super.equals(obj);
    }
    com.cloud.app.proto.UserSetting other = (com.cloud.app.proto.UserSetting) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && getLocale()
        .equals(other.getLocale());
    result = result && getAppearance()
        .equals(other.getAppearance());
    result = result && getMemoVisibility()
        .equals(other.getMemoVisibility());
    result = result && getTelegramUserId()
        .equals(other.getTelegramUserId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + LOCALE_FIELD_NUMBER;
    hash = (53 * hash) + getLocale().hashCode();
    hash = (37 * hash) + APPEARANCE_FIELD_NUMBER;
    hash = (53 * hash) + getAppearance().hashCode();
    hash = (37 * hash) + MEMO_VISIBILITY_FIELD_NUMBER;
    hash = (53 * hash) + getMemoVisibility().hashCode();
    hash = (37 * hash) + TELEGRAM_USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTelegramUserId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cloud.app.proto.UserSetting parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cloud.app.proto.UserSetting parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cloud.app.proto.UserSetting parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cloud.app.proto.UserSetting parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cloud.app.proto.UserSetting parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cloud.app.proto.UserSetting parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cloud.app.proto.UserSetting parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cloud.app.proto.UserSetting parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cloud.app.proto.UserSetting parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cloud.app.proto.UserSetting parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cloud.app.proto.UserSetting parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cloud.app.proto.UserSetting parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cloud.app.proto.UserSetting prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.cloud.app.proto.UserSetting}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.cloud.app.proto.UserSetting)
      com.cloud.app.proto.UserSettingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_UserSetting_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_UserSetting_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloud.app.proto.UserSetting.class, com.cloud.app.proto.UserSetting.Builder.class);
    }

    // Construct using com.cloud.app.proto.UserSetting.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      name_ = "";

      locale_ = "";

      appearance_ = "";

      memoVisibility_ = "";

      telegramUserId_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_UserSetting_descriptor;
    }

    public com.cloud.app.proto.UserSetting getDefaultInstanceForType() {
      return com.cloud.app.proto.UserSetting.getDefaultInstance();
    }

    public com.cloud.app.proto.UserSetting build() {
      com.cloud.app.proto.UserSetting result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.cloud.app.proto.UserSetting buildPartial() {
      com.cloud.app.proto.UserSetting result = new com.cloud.app.proto.UserSetting(this);
      result.name_ = name_;
      result.locale_ = locale_;
      result.appearance_ = appearance_;
      result.memoVisibility_ = memoVisibility_;
      result.telegramUserId_ = telegramUserId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cloud.app.proto.UserSetting) {
        return mergeFrom((com.cloud.app.proto.UserSetting)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cloud.app.proto.UserSetting other) {
      if (other == com.cloud.app.proto.UserSetting.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getLocale().isEmpty()) {
        locale_ = other.locale_;
        onChanged();
      }
      if (!other.getAppearance().isEmpty()) {
        appearance_ = other.appearance_;
        onChanged();
      }
      if (!other.getMemoVisibility().isEmpty()) {
        memoVisibility_ = other.memoVisibility_;
        onChanged();
      }
      if (!other.getTelegramUserId().isEmpty()) {
        telegramUserId_ = other.telegramUserId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cloud.app.proto.UserSetting parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cloud.app.proto.UserSetting) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * The name of the user.
     * Format: users/{username}
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The name of the user.
     * Format: users/{username}
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The name of the user.
     * Format: users/{username}
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the user.
     * Format: users/{username}
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the user.
     * Format: users/{username}
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object locale_ = "";
    /**
     * <pre>
     * The preferred locale of the user.
     * </pre>
     *
     * <code>string locale = 2;</code>
     */
    public java.lang.String getLocale() {
      java.lang.Object ref = locale_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        locale_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The preferred locale of the user.
     * </pre>
     *
     * <code>string locale = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLocaleBytes() {
      java.lang.Object ref = locale_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locale_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The preferred locale of the user.
     * </pre>
     *
     * <code>string locale = 2;</code>
     */
    public Builder setLocale(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      locale_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The preferred locale of the user.
     * </pre>
     *
     * <code>string locale = 2;</code>
     */
    public Builder clearLocale() {
      
      locale_ = getDefaultInstance().getLocale();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The preferred locale of the user.
     * </pre>
     *
     * <code>string locale = 2;</code>
     */
    public Builder setLocaleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      locale_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object appearance_ = "";
    /**
     * <pre>
     * The preferred appearance of the user.
     * </pre>
     *
     * <code>string appearance = 3;</code>
     */
    public java.lang.String getAppearance() {
      java.lang.Object ref = appearance_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appearance_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The preferred appearance of the user.
     * </pre>
     *
     * <code>string appearance = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAppearanceBytes() {
      java.lang.Object ref = appearance_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appearance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The preferred appearance of the user.
     * </pre>
     *
     * <code>string appearance = 3;</code>
     */
    public Builder setAppearance(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appearance_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The preferred appearance of the user.
     * </pre>
     *
     * <code>string appearance = 3;</code>
     */
    public Builder clearAppearance() {
      
      appearance_ = getDefaultInstance().getAppearance();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The preferred appearance of the user.
     * </pre>
     *
     * <code>string appearance = 3;</code>
     */
    public Builder setAppearanceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appearance_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object memoVisibility_ = "";
    /**
     * <pre>
     * The default visibility of the memo.
     * </pre>
     *
     * <code>string memo_visibility = 4;</code>
     */
    public java.lang.String getMemoVisibility() {
      java.lang.Object ref = memoVisibility_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        memoVisibility_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The default visibility of the memo.
     * </pre>
     *
     * <code>string memo_visibility = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMemoVisibilityBytes() {
      java.lang.Object ref = memoVisibility_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memoVisibility_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The default visibility of the memo.
     * </pre>
     *
     * <code>string memo_visibility = 4;</code>
     */
    public Builder setMemoVisibility(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      memoVisibility_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The default visibility of the memo.
     * </pre>
     *
     * <code>string memo_visibility = 4;</code>
     */
    public Builder clearMemoVisibility() {
      
      memoVisibility_ = getDefaultInstance().getMemoVisibility();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The default visibility of the memo.
     * </pre>
     *
     * <code>string memo_visibility = 4;</code>
     */
    public Builder setMemoVisibilityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      memoVisibility_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object telegramUserId_ = "";
    /**
     * <pre>
     * The telegram user id of the user.
     * </pre>
     *
     * <code>string telegram_user_id = 5;</code>
     */
    public java.lang.String getTelegramUserId() {
      java.lang.Object ref = telegramUserId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        telegramUserId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The telegram user id of the user.
     * </pre>
     *
     * <code>string telegram_user_id = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTelegramUserIdBytes() {
      java.lang.Object ref = telegramUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        telegramUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The telegram user id of the user.
     * </pre>
     *
     * <code>string telegram_user_id = 5;</code>
     */
    public Builder setTelegramUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      telegramUserId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The telegram user id of the user.
     * </pre>
     *
     * <code>string telegram_user_id = 5;</code>
     */
    public Builder clearTelegramUserId() {
      
      telegramUserId_ = getDefaultInstance().getTelegramUserId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The telegram user id of the user.
     * </pre>
     *
     * <code>string telegram_user_id = 5;</code>
     */
    public Builder setTelegramUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      telegramUserId_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.cloud.app.proto.UserSetting)
  }

  // @@protoc_insertion_point(class_scope:com.cloud.app.proto.UserSetting)
  private static final com.cloud.app.proto.UserSetting DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cloud.app.proto.UserSetting();
  }

  public static com.cloud.app.proto.UserSetting getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserSetting>
      PARSER = new com.google.protobuf.AbstractParser<UserSetting>() {
    public UserSetting parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserSetting(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserSetting> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserSetting> getParserForType() {
    return PARSER;
  }

  public com.cloud.app.proto.UserSetting getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

