// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.cloud.app.proto;

public interface UserAccessTokenOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cloud.app.proto.UserAccessToken)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string access_token = 1;</code>
   */
  java.lang.String getAccessToken();
  /**
   * <code>string access_token = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();

  /**
   * <code>string description = 2;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>.google.protobuf.Timestamp issued_at = 3;</code>
   */
  boolean hasIssuedAt();
  /**
   * <code>.google.protobuf.Timestamp issued_at = 3;</code>
   */
  com.google.protobuf.Timestamp getIssuedAt();
  /**
   * <code>.google.protobuf.Timestamp issued_at = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getIssuedAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp expires_at = 4;</code>
   */
  boolean hasExpiresAt();
  /**
   * <code>.google.protobuf.Timestamp expires_at = 4;</code>
   */
  com.google.protobuf.Timestamp getExpiresAt();
  /**
   * <code>.google.protobuf.Timestamp expires_at = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpiresAtOrBuilder();
}
