// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.cloud.app.proto;

/**
 * Protobuf type {@code com.cloud.app.proto.UserAccessToken}
 */
public  final class UserAccessToken extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.cloud.app.proto.UserAccessToken)
    UserAccessTokenOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserAccessToken.newBuilder() to construct.
  private UserAccessToken(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserAccessToken() {
    accessToken_ = "";
    description_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserAccessToken(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            accessToken_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (issuedAt_ != null) {
              subBuilder = issuedAt_.toBuilder();
            }
            issuedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(issuedAt_);
              issuedAt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (expiresAt_ != null) {
              subBuilder = expiresAt_.toBuilder();
            }
            expiresAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(expiresAt_);
              expiresAt_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_UserAccessToken_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_UserAccessToken_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cloud.app.proto.UserAccessToken.class, com.cloud.app.proto.UserAccessToken.Builder.class);
  }

  public static final int ACCESS_TOKEN_FIELD_NUMBER = 1;
  private volatile java.lang.Object accessToken_;
  /**
   * <code>string access_token = 1;</code>
   */
  public java.lang.String getAccessToken() {
    java.lang.Object ref = accessToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accessToken_ = s;
      return s;
    }
  }
  /**
   * <code>string access_token = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAccessTokenBytes() {
    java.lang.Object ref = accessToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accessToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 2;</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISSUED_AT_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp issuedAt_;
  /**
   * <code>.google.protobuf.Timestamp issued_at = 3;</code>
   */
  public boolean hasIssuedAt() {
    return issuedAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp issued_at = 3;</code>
   */
  public com.google.protobuf.Timestamp getIssuedAt() {
    return issuedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : issuedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp issued_at = 3;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getIssuedAtOrBuilder() {
    return getIssuedAt();
  }

  public static final int EXPIRES_AT_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp expiresAt_;
  /**
   * <code>.google.protobuf.Timestamp expires_at = 4;</code>
   */
  public boolean hasExpiresAt() {
    return expiresAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp expires_at = 4;</code>
   */
  public com.google.protobuf.Timestamp getExpiresAt() {
    return expiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiresAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp expires_at = 4;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getExpiresAtOrBuilder() {
    return getExpiresAt();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAccessTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accessToken_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
    }
    if (issuedAt_ != null) {
      output.writeMessage(3, getIssuedAt());
    }
    if (expiresAt_ != null) {
      output.writeMessage(4, getExpiresAt());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAccessTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accessToken_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
    }
    if (issuedAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getIssuedAt());
    }
    if (expiresAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getExpiresAt());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cloud.app.proto.UserAccessToken)) {
      return super.equals(obj);
    }
    com.cloud.app.proto.UserAccessToken other = (com.cloud.app.proto.UserAccessToken) obj;

    boolean result = true;
    result = result && getAccessToken()
        .equals(other.getAccessToken());
    result = result && getDescription()
        .equals(other.getDescription());
    result = result && (hasIssuedAt() == other.hasIssuedAt());
    if (hasIssuedAt()) {
      result = result && getIssuedAt()
          .equals(other.getIssuedAt());
    }
    result = result && (hasExpiresAt() == other.hasExpiresAt());
    if (hasExpiresAt()) {
      result = result && getExpiresAt()
          .equals(other.getExpiresAt());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCESS_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getAccessToken().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    if (hasIssuedAt()) {
      hash = (37 * hash) + ISSUED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getIssuedAt().hashCode();
    }
    if (hasExpiresAt()) {
      hash = (37 * hash) + EXPIRES_AT_FIELD_NUMBER;
      hash = (53 * hash) + getExpiresAt().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cloud.app.proto.UserAccessToken parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cloud.app.proto.UserAccessToken parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cloud.app.proto.UserAccessToken parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cloud.app.proto.UserAccessToken parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cloud.app.proto.UserAccessToken parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cloud.app.proto.UserAccessToken parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cloud.app.proto.UserAccessToken parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cloud.app.proto.UserAccessToken parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cloud.app.proto.UserAccessToken parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cloud.app.proto.UserAccessToken parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cloud.app.proto.UserAccessToken parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cloud.app.proto.UserAccessToken parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cloud.app.proto.UserAccessToken prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.cloud.app.proto.UserAccessToken}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.cloud.app.proto.UserAccessToken)
      com.cloud.app.proto.UserAccessTokenOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_UserAccessToken_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_UserAccessToken_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloud.app.proto.UserAccessToken.class, com.cloud.app.proto.UserAccessToken.Builder.class);
    }

    // Construct using com.cloud.app.proto.UserAccessToken.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      accessToken_ = "";

      description_ = "";

      if (issuedAtBuilder_ == null) {
        issuedAt_ = null;
      } else {
        issuedAt_ = null;
        issuedAtBuilder_ = null;
      }
      if (expiresAtBuilder_ == null) {
        expiresAt_ = null;
      } else {
        expiresAt_ = null;
        expiresAtBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cloud.app.proto.UserServiceProto.internal_static_com_cloud_app_proto_UserAccessToken_descriptor;
    }

    public com.cloud.app.proto.UserAccessToken getDefaultInstanceForType() {
      return com.cloud.app.proto.UserAccessToken.getDefaultInstance();
    }

    public com.cloud.app.proto.UserAccessToken build() {
      com.cloud.app.proto.UserAccessToken result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.cloud.app.proto.UserAccessToken buildPartial() {
      com.cloud.app.proto.UserAccessToken result = new com.cloud.app.proto.UserAccessToken(this);
      result.accessToken_ = accessToken_;
      result.description_ = description_;
      if (issuedAtBuilder_ == null) {
        result.issuedAt_ = issuedAt_;
      } else {
        result.issuedAt_ = issuedAtBuilder_.build();
      }
      if (expiresAtBuilder_ == null) {
        result.expiresAt_ = expiresAt_;
      } else {
        result.expiresAt_ = expiresAtBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cloud.app.proto.UserAccessToken) {
        return mergeFrom((com.cloud.app.proto.UserAccessToken)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cloud.app.proto.UserAccessToken other) {
      if (other == com.cloud.app.proto.UserAccessToken.getDefaultInstance()) return this;
      if (!other.getAccessToken().isEmpty()) {
        accessToken_ = other.accessToken_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (other.hasIssuedAt()) {
        mergeIssuedAt(other.getIssuedAt());
      }
      if (other.hasExpiresAt()) {
        mergeExpiresAt(other.getExpiresAt());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cloud.app.proto.UserAccessToken parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cloud.app.proto.UserAccessToken) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object accessToken_ = "";
    /**
     * <code>string access_token = 1;</code>
     */
    public java.lang.String getAccessToken() {
      java.lang.Object ref = accessToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string access_token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string access_token = 1;</code>
     */
    public Builder setAccessToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accessToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string access_token = 1;</code>
     */
    public Builder clearAccessToken() {
      
      accessToken_ = getDefaultInstance().getAccessToken();
      onChanged();
      return this;
    }
    /**
     * <code>string access_token = 1;</code>
     */
    public Builder setAccessTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accessToken_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 2;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 2;</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp issuedAt_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> issuedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp issued_at = 3;</code>
     */
    public boolean hasIssuedAt() {
      return issuedAtBuilder_ != null || issuedAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp issued_at = 3;</code>
     */
    public com.google.protobuf.Timestamp getIssuedAt() {
      if (issuedAtBuilder_ == null) {
        return issuedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : issuedAt_;
      } else {
        return issuedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp issued_at = 3;</code>
     */
    public Builder setIssuedAt(com.google.protobuf.Timestamp value) {
      if (issuedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        issuedAt_ = value;
        onChanged();
      } else {
        issuedAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp issued_at = 3;</code>
     */
    public Builder setIssuedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (issuedAtBuilder_ == null) {
        issuedAt_ = builderForValue.build();
        onChanged();
      } else {
        issuedAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp issued_at = 3;</code>
     */
    public Builder mergeIssuedAt(com.google.protobuf.Timestamp value) {
      if (issuedAtBuilder_ == null) {
        if (issuedAt_ != null) {
          issuedAt_ =
            com.google.protobuf.Timestamp.newBuilder(issuedAt_).mergeFrom(value).buildPartial();
        } else {
          issuedAt_ = value;
        }
        onChanged();
      } else {
        issuedAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp issued_at = 3;</code>
     */
    public Builder clearIssuedAt() {
      if (issuedAtBuilder_ == null) {
        issuedAt_ = null;
        onChanged();
      } else {
        issuedAt_ = null;
        issuedAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp issued_at = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getIssuedAtBuilder() {
      
      onChanged();
      return getIssuedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp issued_at = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getIssuedAtOrBuilder() {
      if (issuedAtBuilder_ != null) {
        return issuedAtBuilder_.getMessageOrBuilder();
      } else {
        return issuedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : issuedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp issued_at = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getIssuedAtFieldBuilder() {
      if (issuedAtBuilder_ == null) {
        issuedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getIssuedAt(),
                getParentForChildren(),
                isClean());
        issuedAt_ = null;
      }
      return issuedAtBuilder_;
    }

    private com.google.protobuf.Timestamp expiresAt_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> expiresAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp expires_at = 4;</code>
     */
    public boolean hasExpiresAt() {
      return expiresAtBuilder_ != null || expiresAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 4;</code>
     */
    public com.google.protobuf.Timestamp getExpiresAt() {
      if (expiresAtBuilder_ == null) {
        return expiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiresAt_;
      } else {
        return expiresAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 4;</code>
     */
    public Builder setExpiresAt(com.google.protobuf.Timestamp value) {
      if (expiresAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expiresAt_ = value;
        onChanged();
      } else {
        expiresAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 4;</code>
     */
    public Builder setExpiresAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (expiresAtBuilder_ == null) {
        expiresAt_ = builderForValue.build();
        onChanged();
      } else {
        expiresAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 4;</code>
     */
    public Builder mergeExpiresAt(com.google.protobuf.Timestamp value) {
      if (expiresAtBuilder_ == null) {
        if (expiresAt_ != null) {
          expiresAt_ =
            com.google.protobuf.Timestamp.newBuilder(expiresAt_).mergeFrom(value).buildPartial();
        } else {
          expiresAt_ = value;
        }
        onChanged();
      } else {
        expiresAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 4;</code>
     */
    public Builder clearExpiresAt() {
      if (expiresAtBuilder_ == null) {
        expiresAt_ = null;
        onChanged();
      } else {
        expiresAt_ = null;
        expiresAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getExpiresAtBuilder() {
      
      onChanged();
      return getExpiresAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getExpiresAtOrBuilder() {
      if (expiresAtBuilder_ != null) {
        return expiresAtBuilder_.getMessageOrBuilder();
      } else {
        return expiresAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : expiresAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getExpiresAtFieldBuilder() {
      if (expiresAtBuilder_ == null) {
        expiresAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getExpiresAt(),
                getParentForChildren(),
                isClean());
        expiresAt_ = null;
      }
      return expiresAtBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.cloud.app.proto.UserAccessToken)
  }

  // @@protoc_insertion_point(class_scope:com.cloud.app.proto.UserAccessToken)
  private static final com.cloud.app.proto.UserAccessToken DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cloud.app.proto.UserAccessToken();
  }

  public static com.cloud.app.proto.UserAccessToken getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserAccessToken>
      PARSER = new com.google.protobuf.AbstractParser<UserAccessToken>() {
    public UserAccessToken parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserAccessToken(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserAccessToken> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserAccessToken> getParserForType() {
    return PARSER;
  }

  public com.cloud.app.proto.UserAccessToken getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

