// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.cloud.app.proto;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cloud.app.proto.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the user.
   * Format: users/{username}
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the user.
   * Format: users/{username}
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>.com.cloud.app.proto.User.Role role = 3;</code>
   */
  int getRoleValue();
  /**
   * <code>.com.cloud.app.proto.User.Role role = 3;</code>
   */
  com.cloud.app.proto.User.Role getRole();

  /**
   * <code>string username = 4;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 4;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string email = 5;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 5;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string nickname = 6;</code>
   */
  java.lang.String getNickname();
  /**
   * <code>string nickname = 6;</code>
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <code>string avatar_url = 7;</code>
   */
  java.lang.String getAvatarUrl();
  /**
   * <code>string avatar_url = 7;</code>
   */
  com.google.protobuf.ByteString
      getAvatarUrlBytes();

  /**
   * <pre>
   *[(google.api.field_behavior) = INPUT_ONLY]
   * </pre>
   *
   * <code>string password = 8;</code>
   */
  java.lang.String getPassword();
  /**
   * <pre>
   *[(google.api.field_behavior) = INPUT_ONLY]
   * </pre>
   *
   * <code>string password = 8;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>.com.cloud.app.proto.RowStatus row_status = 9;</code>
   */
  int getRowStatusValue();
  /**
   * <code>.com.cloud.app.proto.RowStatus row_status = 9;</code>
   */
  com.cloud.app.proto.Common.RowStatus getRowStatus();

  /**
   * <code>.google.protobuf.Timestamp create_time = 10;</code>
   */
  boolean hasCreateTime();
  /**
   * <code>.google.protobuf.Timestamp create_time = 10;</code>
   */
  com.google.protobuf.Timestamp getCreateTime();
  /**
   * <code>.google.protobuf.Timestamp create_time = 10;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp update_time = 11;</code>
   */
  boolean hasUpdateTime();
  /**
   * <code>.google.protobuf.Timestamp update_time = 11;</code>
   */
  com.google.protobuf.Timestamp getUpdateTime();
  /**
   * <code>.google.protobuf.Timestamp update_time = 11;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder();
}
