// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.cloud.app.proto;

public interface UserSettingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cloud.app.proto.UserSetting)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the user.
   * Format: users/{username}
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the user.
   * Format: users/{username}
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The preferred locale of the user.
   * </pre>
   *
   * <code>string locale = 2;</code>
   */
  java.lang.String getLocale();
  /**
   * <pre>
   * The preferred locale of the user.
   * </pre>
   *
   * <code>string locale = 2;</code>
   */
  com.google.protobuf.ByteString
      getLocaleBytes();

  /**
   * <pre>
   * The preferred appearance of the user.
   * </pre>
   *
   * <code>string appearance = 3;</code>
   */
  java.lang.String getAppearance();
  /**
   * <pre>
   * The preferred appearance of the user.
   * </pre>
   *
   * <code>string appearance = 3;</code>
   */
  com.google.protobuf.ByteString
      getAppearanceBytes();

  /**
   * <pre>
   * The default visibility of the memo.
   * </pre>
   *
   * <code>string memo_visibility = 4;</code>
   */
  java.lang.String getMemoVisibility();
  /**
   * <pre>
   * The default visibility of the memo.
   * </pre>
   *
   * <code>string memo_visibility = 4;</code>
   */
  com.google.protobuf.ByteString
      getMemoVisibilityBytes();

  /**
   * <pre>
   * The telegram user id of the user.
   * </pre>
   *
   * <code>string telegram_user_id = 5;</code>
   */
  java.lang.String getTelegramUserId();
  /**
   * <pre>
   * The telegram user id of the user.
   * </pre>
   *
   * <code>string telegram_user_id = 5;</code>
   */
  com.google.protobuf.ByteString
      getTelegramUserIdBytes();
}
