// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.cloud.app.proto;

public final class UserServiceProto {
  private UserServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_ListUsersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_ListUsersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_ListUsersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_ListUsersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_GetUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_GetUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_GetUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_GetUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_CreateUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_CreateUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_CreateUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_CreateUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_UpdateUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_UpdateUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_UpdateUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_UpdateUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_DeleteUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_DeleteUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_DeleteUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_DeleteUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_UserSetting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_UserSetting_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_GetUserSettingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_GetUserSettingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_GetUserSettingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_GetUserSettingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_UpdateUserSettingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_UpdateUserSettingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_UpdateUserSettingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_UpdateUserSettingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_UserAccessToken_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_UserAccessToken_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_ListUserAccessTokensRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_ListUserAccessTokensRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_ListUserAccessTokensResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_ListUserAccessTokensResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_CreateUserAccessTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_CreateUserAccessTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_CreateUserAccessTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_CreateUserAccessTokenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_DeleteUserAccessTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_DeleteUserAccessTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_app_proto_DeleteUserAccessTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_app_proto_DeleteUserAccessTokenResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022user_service.proto\022\023com.cloud.app.prot" +
      "o\032\022store/common.proto\032\034google/api/annota" +
      "tions.proto\032\027google/api/client.proto\032\037go" +
      "ogle/api/field_behavior.proto\032 google/pr" +
      "otobuf/field_mask.proto\032\037google/protobuf" +
      "/timestamp.proto\"\372\002\n\004User\022\014\n\004name\030\001 \001(\t\022" +
      "\n\n\002id\030\002 \001(\005\022,\n\004role\030\003 \001(\0162\036.com.cloud.ap" +
      "p.proto.User.Role\022\020\n\010username\030\004 \001(\t\022\r\n\005e" +
      "mail\030\005 \001(\t\022\020\n\010nickname\030\006 \001(\t\022\022\n\navatar_u" +
      "rl\030\007 \001(\t\022\020\n\010password\030\010 \001(\t\0222\n\nrow_status" +
      "\030\t \001(\0162\036.com.cloud.app.proto.RowStatus\022/" +
      "\n\013create_time\030\n \001(\0132\032.google.protobuf.Ti" +
      "mestamp\022/\n\013update_time\030\013 \001(\0132\032.google.pr" +
      "otobuf.Timestamp\";\n\004Role\022\024\n\020ROLE_UNSPECI" +
      "FIED\020\000\022\010\n\004HOST\020\001\022\t\n\005ADMIN\020\002\022\010\n\004USER\020\003\"\022\n" +
      "\020ListUsersRequest\"=\n\021ListUsersResponse\022(" +
      "\n\005users\030\001 \003(\0132\031.com.cloud.app.proto.User" +
      "\"\036\n\016GetUserRequest\022\014\n\004name\030\001 \001(\t\":\n\017GetU" +
      "serResponse\022\'\n\004user\030\001 \001(\0132\031.com.cloud.ap" +
      "p.proto.User\"<\n\021CreateUserRequest\022\'\n\004use" +
      "r\030\001 \001(\0132\031.com.cloud.app.proto.User\"=\n\022Cr" +
      "eateUserResponse\022\'\n\004user\030\001 \001(\0132\031.com.clo" +
      "ud.app.proto.User\"m\n\021UpdateUserRequest\022\'" +
      "\n\004user\030\001 \001(\0132\031.com.cloud.app.proto.User\022" +
      "/\n\013update_mask\030\002 \001(\0132\032.google.protobuf.F" +
      "ieldMask\"=\n\022UpdateUserResponse\022\'\n\004user\030\001" +
      " \001(\0132\031.com.cloud.app.proto.User\"!\n\021Delet" +
      "eUserRequest\022\014\n\004name\030\001 \001(\t\"\024\n\022DeleteUser" +
      "Response\"r\n\013UserSetting\022\014\n\004name\030\001 \001(\t\022\016\n" +
      "\006locale\030\002 \001(\t\022\022\n\nappearance\030\003 \001(\t\022\027\n\017mem" +
      "o_visibility\030\004 \001(\t\022\030\n\020telegram_user_id\030\005" +
      " \001(\t\"%\n\025GetUserSettingRequest\022\014\n\004name\030\001 " +
      "\001(\t\"K\n\026GetUserSettingResponse\0221\n\007setting" +
      "\030\001 \001(\0132 .com.cloud.app.proto.UserSetting" +
      "\"~\n\030UpdateUserSettingRequest\0221\n\007setting\030" +
      "\001 \001(\0132 .com.cloud.app.proto.UserSetting\022" +
      "/\n\013update_mask\030\002 \001(\0132\032.google.protobuf.F" +
      "ieldMask\"N\n\031UpdateUserSettingResponse\0221\n" +
      "\007setting\030\001 \001(\0132 .com.cloud.app.proto.Use" +
      "rSetting\"\233\001\n\017UserAccessToken\022\024\n\014access_t" +
      "oken\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022-\n\tissue" +
      "d_at\030\003 \001(\0132\032.google.protobuf.Timestamp\022." +
      "\n\nexpires_at\030\004 \001(\0132\032.google.protobuf.Tim" +
      "estamp\"+\n\033ListUserAccessTokensRequest\022\014\n" +
      "\004name\030\001 \001(\t\"[\n\034ListUserAccessTokensRespo" +
      "nse\022;\n\raccess_tokens\030\001 \003(\0132$.com.cloud.a" +
      "pp.proto.UserAccessToken\"q\n\034CreateUserAc" +
      "cessTokenRequest\022\014\n\004name\030\001 \001(\t\022\023\n\013descri" +
      "ption\030\002 \001(\t\022.\n\nexpires_at\030\003 \001(\0132\032.google" +
      ".protobuf.Timestamp\"[\n\035CreateUserAccessT" +
      "okenResponse\022:\n\014access_token\030\001 \001(\0132$.com" +
      ".cloud.app.proto.UserAccessToken\"B\n\034Dele" +
      "teUserAccessTokenRequest\022\014\n\004name\030\001 \001(\t\022\024" +
      "\n\014access_token\030\002 \001(\t\"\037\n\035DeleteUserAccess" +
      "TokenResponse2\316\010\n\013UserService\022\\\n\tListUse" +
      "rs\022%.com.cloud.app.proto.ListUsersReques" +
      "t\032&.com.cloud.app.proto.ListUsersRespons" +
      "e\"\000\022V\n\007GetUser\022#.com.cloud.app.proto.Get" +
      "UserRequest\032$.com.cloud.app.proto.GetUse" +
      "rResponse\"\000\022_\n\nCreateUser\022&.com.cloud.ap" +
      "p.proto.CreateUserRequest\032\'.com.cloud.ap" +
      "p.proto.CreateUserResponse\"\000\022_\n\nUpdateUs" +
      "er\022&.com.cloud.app.proto.UpdateUserReque" +
      "st\032\'.com.cloud.app.proto.UpdateUserRespo" +
      "nse\"\000\022_\n\nDeleteUser\022&.com.cloud.app.prot" +
      "o.DeleteUserRequest\032\'.com.cloud.app.prot" +
      "o.DeleteUserResponse\"\000\022k\n\016GetUserSetting" +
      "\022*.com.cloud.app.proto.GetUserSettingReq" +
      "uest\032+.com.cloud.app.proto.GetUserSettin" +
      "gResponse\"\000\022t\n\021UpdateUserSetting\022-.com.c" +
      "loud.app.proto.UpdateUserSettingRequest\032" +
      "..com.cloud.app.proto.UpdateUserSettingR" +
      "esponse\"\000\022}\n\024ListUserAccessTokens\0220.com." +
      "cloud.app.proto.ListUserAccessTokensRequ" +
      "est\0321.com.cloud.app.proto.ListUserAccess" +
      "TokensResponse\"\000\022\200\001\n\025CreateUserAccessTok" +
      "en\0221.com.cloud.app.proto.CreateUserAcces" +
      "sTokenRequest\0322.com.cloud.app.proto.Crea" +
      "teUserAccessTokenResponse\"\000\022\200\001\n\025DeleteUs" +
      "erAccessToken\0221.com.cloud.app.proto.Dele" +
      "teUserAccessTokenRequest\0322.com.cloud.app" +
      ".proto.DeleteUserAccessTokenResponse\"\000B\024" +
      "B\020UserServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.cloud.app.proto.Common.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.protobuf.FieldMaskProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_com_cloud_app_proto_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_cloud_app_proto_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_User_descriptor,
        new java.lang.String[] { "Name", "Id", "Role", "Username", "Email", "Nickname", "AvatarUrl", "Password", "RowStatus", "CreateTime", "UpdateTime", });
    internal_static_com_cloud_app_proto_ListUsersRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_cloud_app_proto_ListUsersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_ListUsersRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_cloud_app_proto_ListUsersResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_cloud_app_proto_ListUsersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_ListUsersResponse_descriptor,
        new java.lang.String[] { "Users", });
    internal_static_com_cloud_app_proto_GetUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_cloud_app_proto_GetUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_GetUserRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_cloud_app_proto_GetUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_cloud_app_proto_GetUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_GetUserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_com_cloud_app_proto_CreateUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_cloud_app_proto_CreateUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_CreateUserRequest_descriptor,
        new java.lang.String[] { "User", });
    internal_static_com_cloud_app_proto_CreateUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_cloud_app_proto_CreateUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_CreateUserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_com_cloud_app_proto_UpdateUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_cloud_app_proto_UpdateUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_UpdateUserRequest_descriptor,
        new java.lang.String[] { "User", "UpdateMask", });
    internal_static_com_cloud_app_proto_UpdateUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_cloud_app_proto_UpdateUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_UpdateUserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_com_cloud_app_proto_DeleteUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_cloud_app_proto_DeleteUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_DeleteUserRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_cloud_app_proto_DeleteUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_cloud_app_proto_DeleteUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_DeleteUserResponse_descriptor,
        new java.lang.String[] { });
    internal_static_com_cloud_app_proto_UserSetting_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_cloud_app_proto_UserSetting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_UserSetting_descriptor,
        new java.lang.String[] { "Name", "Locale", "Appearance", "MemoVisibility", "TelegramUserId", });
    internal_static_com_cloud_app_proto_GetUserSettingRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_cloud_app_proto_GetUserSettingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_GetUserSettingRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_cloud_app_proto_GetUserSettingResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_cloud_app_proto_GetUserSettingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_GetUserSettingResponse_descriptor,
        new java.lang.String[] { "Setting", });
    internal_static_com_cloud_app_proto_UpdateUserSettingRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_cloud_app_proto_UpdateUserSettingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_UpdateUserSettingRequest_descriptor,
        new java.lang.String[] { "Setting", "UpdateMask", });
    internal_static_com_cloud_app_proto_UpdateUserSettingResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_cloud_app_proto_UpdateUserSettingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_UpdateUserSettingResponse_descriptor,
        new java.lang.String[] { "Setting", });
    internal_static_com_cloud_app_proto_UserAccessToken_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_cloud_app_proto_UserAccessToken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_UserAccessToken_descriptor,
        new java.lang.String[] { "AccessToken", "Description", "IssuedAt", "ExpiresAt", });
    internal_static_com_cloud_app_proto_ListUserAccessTokensRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_cloud_app_proto_ListUserAccessTokensRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_ListUserAccessTokensRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_cloud_app_proto_ListUserAccessTokensResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_cloud_app_proto_ListUserAccessTokensResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_ListUserAccessTokensResponse_descriptor,
        new java.lang.String[] { "AccessTokens", });
    internal_static_com_cloud_app_proto_CreateUserAccessTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_cloud_app_proto_CreateUserAccessTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_CreateUserAccessTokenRequest_descriptor,
        new java.lang.String[] { "Name", "Description", "ExpiresAt", });
    internal_static_com_cloud_app_proto_CreateUserAccessTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_cloud_app_proto_CreateUserAccessTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_CreateUserAccessTokenResponse_descriptor,
        new java.lang.String[] { "AccessToken", });
    internal_static_com_cloud_app_proto_DeleteUserAccessTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_cloud_app_proto_DeleteUserAccessTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_DeleteUserAccessTokenRequest_descriptor,
        new java.lang.String[] { "Name", "AccessToken", });
    internal_static_com_cloud_app_proto_DeleteUserAccessTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_cloud_app_proto_DeleteUserAccessTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_app_proto_DeleteUserAccessTokenResponse_descriptor,
        new java.lang.String[] { });
    com.cloud.app.proto.Common.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
