server:
  port: 8020

spring:
  datasource:
    url: jdbc:mysql://bj-cdb-58e3dg4u.sql.tencentcdb.com:63774/cloud?userSSL=false
    #    url: jdbc:mysql://mysql:3306/pig?useSSL=false
    username: root
    password: Jingran08!
    driver-class-name: com.mysql.cj.jdbc.Driver
    shardingsphere:
      sharding:
        default-database-strategy:
        tables:

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
#  mapper-locations: mybatis.mapper-locations=classpath*:**/mappers/*Mapper.xml
  type-aliases-package: com.cloud.register.domain
  configuration:
    map-underscore-to-camel-case: true
