server:
  port: 10010

spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos地址
    gateway:
      routes:
        - id: cloud-order-service # 路由标示，必须唯一
          uri: lb://cloud-order-service # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/order/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: cloud-app-service
          uri: lb://cloud-order-service
          predicates:
            - Path=/app/**
      default-filters:
        - AddRequestHeader=Truth,Itcast is freaking awesome!