server:
  port: 8012
grpc:
  server:
    port: 443
    security:
      enabled: true
#      cert-chain: classpath:cert/server-cert.pem
#      private-key: file:../cloud-app-service/src/main/resources/cert/server-key.pem
#      private-key: classpath:server.key
#      certificate-chain: classpath:server.crt
      private-key: classpath:cert/localhost-443-key.pem
      certificate-chain: classpath:cert/localhost-443.pem

spring:
  application:
    name: cloud-app-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
       :
        username: nacos
        password: nacos
        namespace: public


cloud-order-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - cloud-order-service
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数