server:
  port: 8030

spring:
  datasource:
    url: jdbc:mysql://bj-cdb-58e3dg4u.sql.tencentcdb.com:63774/basicdata?userSSL=false
    #    url: jdbc:mysql://mysql:3306/pig?useSSL=false
    username: root
    password: Jingran08!
    driver-class-name: com.mysql.cj.jdbc.Driver
    shardingsphere:
      sharding:
        default-database-strategy:
        tables:

  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器端口号
    port: 6379
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: ""
    lettuce:
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20

  elasticsearch:
    rest:
      uris: 82.157.203.124:9200
      read-timeout: 30s
      connection-timeout: 5s
      username: elastic
      password: Jingran08!

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
#  mapper-locations: mybatis.mapper-locations=classpath*:**/mappers/*Mapper.xml
  type-aliases-package: com.cloud.register.domain
  configuration:
    map-underscore-to-camel-case: true
